### ISSUE TITLE
Shell did not start up in time as we did not receive any response.  Welcome to JumpServer SSH Server

### ISSUE THREAD

**Issue by maochengliang** [xpipe-io/xpipe-webtop#6]
<img width="708" height="294" alt="Image" src="https://github.com/user-attachments/assets/7d9f57be-b7dc-4025-bdeb-bf31461a7540" />

**Comment by crschnick** [comment]
This issue is fixed in XPipe 17 with the added configuration for jump servers. It is available for testing at: https://github.com/xpipe-io/xpipe-ptb and will be released soon

**Comment by maochengliang** [comment]
> 此问题已在 XPipe 17 中修复，并添加了跳转服务器配置。您可以访问https://github.com/xpipe-io/xpipe-ptb进行测试，并将于近期发布。

hi!
I have downloaded the latest PTB installation package, but this problem still exists
<img width="1264" height="721" alt="Image" src="https://github.com/user-attachments/assets/c4bcd962-78ae-4857-a755-3e046ccc466d" />

<img width="740" height="281" alt="Image" src="https://github.com/user-attachments/assets/278a0ad9-8e72-45f6-83a9-ea0f4f692efb" />

**Comment by crschnick** [comment]
In your case, you have to set the system as a jump server and limited system in the advanced settings: 

<img width="671" height="702" alt="Image" src="https://github.com/user-attachments/assets/85256b9d-8729-4e8c-b692-2ed401e7782a" />

Then, you can use this jump server as a gateway when creating other connections. The PTB documentation is available here: https://docs-ptb.xpipe.io/guide/ssh#gateways-and-jump-servers

**Comment by maochengliang** [comment]
> 对于您来说，您必须在高级设置中将系统设置为跳转服务器和受限系统：
> 
> <img alt="图像" width="671" height="702" src="https://private-user-images.githubusercontent.com/72509152/466321896-85256b9d-8729-4e8c-b692-2ed401e7782a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI1NTg4NzQsIm5iZiI6MTc1MjU1ODU3NCwicGF0aCI6Ii83MjUwOTE1Mi80NjYzMjE4OTYtODUyNTZiOWQtODcyOS00ZThjLWI2OTItMmVkNDAxZTc3ODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE1VDA1NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZTZiMTg4ODViMzBlMmRkNzUwZWM4NjAyMmI4NDJiMTY0MGEyYWJhZWRkYzNiMzM2MTdkYmJjZjdmNmE1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mu6awrAbUiSStZ_wnEdx1xBnvFBcRdC-XfX0jpq_qks">
> 然后，您可以在创建其他连接时使用此跳转服务器作为网关。PTB 文档位于：https://docs-ptb.xpipe.io/guide/ssh#gateways-and-jump-servers

Yes, it will be normal if I added it, thanks

**Comment by crschnick** [comment]
This is now fully released in 17.0
